kotlinx.serialization to mojang serialization bridge
QuiltMC/quilt-kotlin-libraries pull request #49
Opened 2022-10-13 13:22 UTC by Cypher121

Adds a new feature allowing the following:

* Conversion of KSerializers (generated by Serializable annotations) to Codecs
* Usage of pre-existing codecs for generating new ones
* Extensive format configuration on a per-type or per-codec basis.

User and implementer documentation can be found within the package folder in serialization.md

Some things that may warrant more work:
* Documentation, either overview in .md or KDoc and comments on individual issues
* Making tests run in an actual test engine. Requires resolving loom dependency issues (probably #35).
* Decoder/Encoder state management. May be a sane way around ElementOptions hell.
* More tests. Even more tests. MORE. Any ideas welcome, especially those with test code in them.

2022-10-17 01:59 UTC, Oliver-makes-code approved these changes
LGTM

2022-10-17 02:04 UTC, PotatoPresident approved these changes
This is awesome! Definitely going to migrate my codecs to this

2022-10-17 03:50 UTC, SilverAndro requested changes

2022-10-17 03:50 UTC, SilverAndro commented on wrapper/minecraft/src/main/kotlin/org/quiltmc/qkl/wrapper/minecraft/serialization/internal/SerializerCodec.kt
> +internal class SerializerCodec<A>(
This class should have toString implemented for debugging purposes, as is it just returns the jvm representation

![image](https://user-images.githubusercontent.com/52360088/196085367-401503eb-842a-4185-a25f-ba42916037da.png)

2022-10-17 04:13 UTC, SilverAndro commented
Seems to work in my mod (REA usage specifically tested) so other than the minor thing about toString im happy to approve, absolutely incredible work!

2022-10-17 04:59 UTC, SilverAndro approved these changes

2022-10-26 20:22 UTC, PotatoPresident approved these changes

2022-11-02 18:23 UTC, NoComment1105 approved these changes

2022-11-02 18:34 UTC, Cypher121 commented on gradle/libs.versions.toml
> +serialization_plugin = "1.7.10" # usually same as kotlin but can lag behind
```suggestion
serialization_plugin = "1.7.20" # usually same as kotlin but can lag behind
```

2022-11-02 18:36 UTC, Cypher121 commented on gradle/libs.versions.toml
>  serialization = "1.4.0"
```suggestion
serialization = "1.4.1"
```

2022-11-13 08:04 UTC, merged