Add Registry DSL
QuiltMC/quilt-kotlin-libraries pull request #7
Opened 2022-06-09 19:07 UTC by Oliver-makes-code

This PR provides a Registry DSL for organizing registration
Example:
```kt
fun register() {
  RegistryDsl("modid") {
    Registry.BLOCK {
      Block(/*...*/) withName "block_1" toRegistry this
    }
    Block(/*...*/) withName "block_2" toRegistry Registry.BLOCK
  }
  Block(/*...*/) withId Identifier("test", "block_3") toRegistry Registry.BLOCK
}
```

Closes #5

2022-06-09 19:09 UTC, Oliver-makes-code commented
It's also important to note that it works with all registries, not just BLOCK

2022-06-09 20:03 UTC, Oliver-makes-code commented
> I know this would increase api complexity but... Would it be possible to have the following
> 
> ```kotlin
> Registry.BLOCK {
>     Block(/*...*/) withName "block_1"
> }
> ```
> 
> instead of
> 
> ```kotlin
> Registry.BLOCK {
>     Block(/*...*/) withName "block_1" toRegistry this
> }
> ```

Currently, that can only been done with `context`, which is experimental right now

2022-06-09 22:32 UTC, Kroppeb commented
> Currently, that can only been done with `context`, which is experimental right now

Mmh, I feel like this is possible without `context`

2022-06-09 22:33 UTC, sschr15 commented
> Mmh, I feel like this is possible without `context`

In that particular case, I believe (though I haven't looked deeply into it yet) that it is possible, but in some other scenarios, context receivers are very handy

2022-06-09 22:34 UTC, Oliver-makes-code commented
> > Mmh, I feel like this is possible without `context`
> 
> In that particular case, I believe (though I haven't looked deeply into it yet) that it is possible, but in some other scenarios, context receivers are very handy

How would I go about doing that then?

2022-06-09 22:35 UTC, Kroppeb commented
> How would I go about doing that then?

time to clone, and write some actual kotlin code for the first time in too long

2022-06-09 22:36 UTC, sschr15 commented
`Registry.() -> Unit` or a similar signature for the passed parameter

2022-06-09 22:38 UTC, sschr15 commented
Oh I already see that's what it is; in that case it should already work

2022-06-09 22:39 UTC, sschr15 commented
oh wait I completely misunderstood it all

2022-06-09 22:39 UTC, SilverAndro commented
[I dont think it is possible?](https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS42LjIxIiwiY29kZSI6ImNsYXNzIFNvbWVUeXBlIHtcbiAgICBpbmZpeCBmdW4gZG9UaGluZyhvdGhlcjogSW50KSB7XG4gICAgICAgIHByaW50bG4oXCJBICRvdGhlciAkdGhpc1wiKVxuICAgIH1cbn1cblxuY2xhc3MgU29tZVdyYXBwZXIoYWN0aW9uOiBTb21lV3JhcHBlci4oKS0+VW5pdCkge1xuICAgIGluaXQge1xuICAgICAgICBhY3Rpb24oKVxuICAgIH1cbiAgICBcbiAgICBpbmZpeCBmdW4gU29tZVR5cGUuZG9UaGluZyhvdGhlcjogSW50KSB7XG4gICAgICAgIHByaW50bG4oXCJCICRvdGhlciAkdGhpc1wiKVxuICAgIH1cbiAgICBcbiAgICBpbmZpeCBmdW4gU29tZVR5cGUuZG9PdGhlclRoaW5nKG90aGVyOiBJbnQpIHtcbiAgICAgICAgcHJpbnRsbihcIkMgJG90aGVyICR0aGlzXCIpXG4gICAgfVxufVxuXG5mdW4gbWFpbigpIHtcbiAgICBTb21lVHlwZSgpIGRvVGhpbmcgMVxuICAgIFNvbWVXcmFwcGVyIHtcbiAgICAgICAgU29tZVR5cGUoKSBkb1RoaW5nIDJcbiAgICAgICAgU29tZVR5cGUoKSBkb090aGVyVGhpbmcgM1xuICAgICAgICAvLyBJbnZhbGlkOiBTb21lVHlwZSgpIHRoaXMuZG9UaGluZyAyXG4gICAgfVxufSIsInBsYXRmb3JtIjoiamF2YSIsImFyZ3MiOiIifQ==) Cant find a way to access the wrapper one if its the same, and even then the infix function ends up overwriting `this`, meaning you'd have to manage to hack around that by making everything run on one `object`, which wouldn't be thread safe.

2022-06-09 22:41 UTC, sschr15 commented
The only reasonable option that I could see to remove the terminating call would be to make every call terminating, which would not work well if attributes get thrown in as well

2022-06-09 22:42 UTC, sschr15 commented
That or a temporary state could be kept, and as soon as the state is no longer touched, it's automatically added to the registry

2022-06-09 23:58 UTC, Oliver-makes-code commented
Edited the example in the first comment to match changes made in the latest commit

2022-06-10 00:08 UTC, Oliver-makes-code commented
I think how it is currently is its final form, so once all 3 requested reviewers review positively I think it should be safe to merge

2022-06-10 00:20 UTC, SilverAndro requested changes
Looks good just a few documentation nitpicks

2022-06-10 00:20 UTC, SilverAndro commented on wrapper/main/src/main/kotlin/org/quiltmc/qkl/wrapper/main/registry/RegistryDsl.kt
> + * Represent an action with a registry
Small nitpick: Should probably be `Represents`

2022-06-10 00:20 UTC, SilverAndro commented on wrapper/main/src/main/kotlin/org/quiltmc/qkl/wrapper/main/registry/RegistryDsl.kt
> + * Registry DSL class, used to register object more cleanly
Small nitpick: Should probably be `objects`

2022-06-10 00:20 UTC, SilverAndro commented on wrapper/main/src/main/kotlin/org/quiltmc/qkl/wrapper/main/registry/RegistryDsl.kt
> +     * Registers an object with a given name
Probably worth adding its behavior with/without a modid, i.e make it clear how the `name`  param is used

2022-06-10 01:01 UTC, SilverAndro approved these changes

2022-06-10 01:22 UTC, PotatoPresident approved these changes
Looks good to me

2022-06-10 03:41 UTC, leocth approved these changes
LGTM, but could we consider the possibility of having a DeferredRegistry-style DSL, as mentioned by Silver in Discord?

```kt
object MyContent : Register("modid") {
  val SOME_ITEM by item("magic", ItemInstance())
  val SOME_BLOCK by block("magic_block", BlockInstance())
}
```

2022-06-10 03:43 UTC, Oliver-makes-code commented
> ```kotlin
> object MyContent : Register("modid") {
>   val SOME_ITEM by item("magic", ItemInstance())
>   val SOME_BLOCK by block("magic_block", BlockInstance())
> }
> ```

The issue with this kind of system is that it doesn't have automatic support with third party registries

2022-06-10 03:49 UTC, leocth commented
> > ```kotlin
> > object MyContent : Register("modid") {
> >   val SOME_ITEM by item("magic", ItemInstance())
> >   val SOME_BLOCK by block("magic_block", BlockInstance())
> > }
> > ```
> 
> The issue with this kind of system is that it doesn't have automatic support with third party registries

I mean, you could just add extension methods to the `Register` class but I do see your point - i just think it's a bit neater to have the item declaration, initialization and registration in one place

2022-06-10 04:06 UTC, NoComment1105 approved these changes
LGTM 👍🏼

2022-06-10 06:31 UTC, Leo40Git approved these changes

2022-06-15 04:27 UTC, merged