Mod publishing on release creation
QuiltMC/quilt-kotlin-libraries pull request #74
Opened 2023-06-14 22:52 UTC by sschr15

Hopefully it's set up correctly. Please tell me what's wrong if it's not right

2023-06-15 04:29 UTC, Oliver-makes-code requested changes

2023-06-15 04:29 UTC, Oliver-makes-code commented on build.gradle.kts
> +    projectId.set("qkl")
This should be the project id, lwVhp9o5

2023-06-15 04:29 UTC, Oliver-makes-code commented on build.gradle.kts
> +    }
Should contain qsl

2023-06-15 04:29 UTC, Oliver-makes-code commented on build.gradle.kts
> +        })
Should also contain qsl

2023-06-15 04:29 UTC, Oliver-makes-code commented on build.gradle.kts
> +    file.set(tasks.remapJar.get().archiveFile)
Why does cf have core added but nor mr?

2023-06-15 05:21 UTC, PotatoPresident commented on build.gradle.kts
> +    }
slug is valid

2023-06-19 03:14 UTC, Oliver-makes-code approved these changes

2023-06-19 06:37 UTC, NoComment1105 approved these changes
Looks solid. Good work

2023-06-20 16:49 UTC, merged